#!/usr/bin/env node
/**
 * Bundle every `src/lambdas/*` entry into `dist-lambdas/<name>/index.mjs`
 * via esbuild. The construct ships the resulting directories as
 * `lambda.Code.fromAsset(<dir>)`, so consumers of `@mcp-savvy/cdk`
 * don't need to install `jose` / `@aws-sdk/client-bedrock-agentcore`
 * themselves — esbuild bakes them into the Lambda zip at our build
 * time.
 *
 * Why ESM output:
 *   - Source is TS-ESM. Output as `index.mjs` so the Lambda runtime
 *     loads ESM directly (Node 22 supports `.mjs` natively).
 *
 * Why we exclude `@aws-sdk/*` from the bundle:
 *   - The Lambda Node 22 runtime ships AWS SDK v3 as a builtin, but
 *     `@aws-sdk/client-bedrock-agentcore` is NOT yet in the runtime
 *     bundle (the AgentCore Identity APIs are recent). So we DO
 *     bundle it, while leaving the older clients (sts, sso, etc.)
 *     marked external for a smaller zip.
 */

import * as esbuild from 'esbuild';
import { existsSync, readdirSync, statSync, unlinkSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(HERE, '..');
const LAMBDA_SRC_DIR = resolve(PACKAGE_ROOT, 'src', 'lambdas');
const LAMBDA_OUT_DIR = resolve(PACKAGE_ROOT, 'dist-lambdas');

/**
 * Modules we leave un-bundled. The Node 22 runtime provides the
 * core AWS SDK clients — bundling them just inflates the zip.
 * `@aws-sdk/client-bedrock-agentcore` is intentionally NOT in this
 * list: AgentCore Identity is too new to be runtime-bundled, so we
 * pull it into the Lambda zip ourselves.
 *
 * Per-lambda override: `register-return-urls` bundles the entire
 * dependency tree (no externals). The
 * `@aws-sdk/client-bedrock-agentcore-control` package's
 * `runtimeConfig.js` synchronously `require`s
 * `@aws-sdk/credential-provider-node` at load, and a bundled ESM
 * Lambda's CJS shim cannot resolve runtime-provided externals.
 * Bundling everything (~2 MB unzipped) avoids the trap.
 */
const EXTERNAL_MODULES = [
    '@aws-sdk/client-sts',
    '@aws-sdk/client-sso',
    '@aws-sdk/client-sso-oidc',
    '@aws-sdk/credential-provider-node',
    '@aws-sdk/credential-providers',
];

/** Lambdas that bundle everything (no externals) AND emit CJS. */
const FULL_BUNDLE_LAMBDAS = new Set([
    'register-return-urls',
    'complete-session',
    // kb-ingest pulls in @aws-sdk/client-bedrock-agent, whose
    // @smithy/node-http-handler synchronously require()s
    // `node:https` at load — the same ESM-shim trap documented for
    // the other full-bundle lambdas. Emit CJS.
    'kb-ingest',
]);

function listLambdas() {
    return readdirSync(LAMBDA_SRC_DIR).filter((entry) => {
        const full = join(LAMBDA_SRC_DIR, entry);
        return statSync(full).isDirectory();
    });
}

/** Remove any stale `index.{mjs,cjs}` files in the lambda's output dir. */
function cleanLambdaOutDir(outDir) {
    if (!existsSync(outDir)) return;
    for (const name of readdirSync(outDir)) {
        if (name === 'index.mjs' || name === 'index.cjs') {
            unlinkSync(join(outDir, name));
        }
    }
}

async function buildOne(name) {
    const entryPoint = join(LAMBDA_SRC_DIR, name, 'index.ts');
    const fullBundle = FULL_BUNDLE_LAMBDAS.has(name);
    // Full-bundle lambdas emit CJS so deeply-nested transitive
    // CommonJS modules (e.g. @smithy/node-http-handler,
    // @aws-crypto/crc32) can call `require('node:built-in')`
    // without esbuild's CJS-from-ESM shim misrouting it. Each
    // affected dep's failure mode is `Dynamic require of "X" is not
    // supported` at Lambda init.
    const format = fullBundle ? 'cjs' : 'esm';
    const ext = fullBundle ? 'cjs' : 'mjs';
    const outDir = join(LAMBDA_OUT_DIR, name);
    const outFile = join(outDir, `index.${ext}`);
    // Clean prior output so a switch from `.mjs` to `.cjs` (or back)
    // doesn't leave both files in the asset directory — Lambda
    // resolves `index.handler` against any matching extension and
    // would otherwise pick up the stale one.
    cleanLambdaOutDir(outDir);
    const external = fullBundle ? [] : EXTERNAL_MODULES;
    await esbuild.build({
        entryPoints: [entryPoint],
        outfile: outFile,
        bundle: true,
        platform: 'node',
        target: 'node22',
        format,
        sourcemap: false,
        minify: false,
        external,
        // ESM output needs explicit `import.meta.url` -> `__dirname`
        // shims if the source uses them. Our Lambda sources don't.
        banner: {
            js:
                '// mcp-savvy lambda bundle — generated by ' +
                'packages/cdk/scripts/build-lambdas.mjs.\n' +
                '// Do not edit by hand.',
        },
    });
}

const lambdas = listLambdas();
if (lambdas.length === 0) {
    console.error('No lambda entry-point directories found under src/lambdas/');
    process.exit(1);
}

await Promise.all(lambdas.map(buildOne));
process.stdout.write(`bundled ${lambdas.length} lambda(s): ${lambdas.join(', ')}\n`);
